# site settings
title: Branson Fox
subtitle: Research and Resources
email: branson.fox@slu.edu
description: The personal website of Branson Fox
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:Branson Fox
city: Saint Louis
state: M0
zip_code: 63103
country: United States of America
phone: (314) 920-3311

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url:https://github.com/bransonf
twitter_url: https://twitter.com/Branson_Fox
linkedin_url: https://www.linkedin.com/in/bransonf/

# build settings
markdown: kramdown

sass:
  style: compressed
